In [7]:
import os
from glob import glob
import ntpath
import pandas as pd
import numpy as np

In [2]:
private_ground_truth_dataframe = r"D:/deepfakes/aws/labels_updated.csv"
private_predicted_dataframe = r"D:\deepfakes\inference\final_efficient_net4_private_test_set.csv"

In [3]:
truth_df = pd.read_csv(private_ground_truth_dataframe)
predicted_df = pd.read_csv(private_predicted_dataframe)

In [5]:
truth_df

            filename  label
0     aalscayrfi.mp4      0
1     aamrozxzsq.mp4      1
2     aaoqanfmgd.mp4      1
3     aaqkmjtoby.mp4      1
4     aarpyivfys.mp4      0
...              ...    ...
3995  zzkhgelrxm.mp4      1
3996  zzoqoqsqtf.mp4      1
3997  zztotvpkjc.mp4      0
3998  zztsycpujv.mp4      1
3999  zzyawcrxmh.mp4      0

[4000 rows x 2 columns]

In [4]:
predicted_df

            filename     label
0     aalscayrfi.mp4  0.010000
1     aamrozxzsq.mp4  0.604828
2     aaoqanfmgd.mp4  0.990000
3     aaqkmjtoby.mp4  0.010000
4     aarpyivfys.mp4  0.011211
...              ...       ...
3981  zzkhgelrxm.mp4  0.986409
3982  zzoqoqsqtf.mp4  0.010000
3983  zztotvpkjc.mp4  0.073738
3984  zztsycpujv.mp4  0.986140
3985  zzyawcrxmh.mp4  0.010000

[3986 rows x 2 columns]

In [10]:
filenames_truth = truth_df.filename
filenames_predicted = predicted_df.filename
missing = np.setdiff1d(filenames_truth, filenames_predicted)
missing

array(['cwalapnial.mp4', 'czzakkzofn.mp4', 'gfeuzhprhw.mp4',
       'hnhbzeexxz.mp4', 'hxozqwbklb.mp4', 'kcttdvayfc.mp4',
       'nrcyxcmbhm.mp4', 'qvukdbrllv.mp4', 'rjlzwkevjm.mp4',
       'uwstkmtpsc.mp4', 'yhftnhzpup.mp4', 'yocnuehmzm.mp4',
       'yykmjpgjzz.mp4', 'zhttbbqhtf.mp4'], dtype=object)

In [11]:
missing_df = truth_df[truth_df['filename'].isin(missing)]

In [12]:
missing_df

            filename  label
441   cwalapnial.mp4      0
465   czzakkzofn.mp4      0
944   gfeuzhprhw.mp4      1
1157  hnhbzeexxz.mp4      0
1215  hxozqwbklb.mp4      0
1558  kcttdvayfc.mp4      1
2109  nrcyxcmbhm.mp4      0
2597  qvukdbrllv.mp4      1
2689  rjlzwkevjm.mp4      0
3223  uwstkmtpsc.mp4      0
3755  yhftnhzpup.mp4      0
3793  yocnuehmzm.mp4      1
3845  yykmjpgjzz.mp4      1
3907  zhttbbqhtf.mp4      1

In [13]:
new_predicted_df = pd.concat([predicted_df, missing_df], ignore_index=True)

In [15]:
new_predicted_df = new_predicted_df.sort_values(by=["filename"], ignore_index=True)

In [16]:
new_predicted_df

            filename     label
0     aalscayrfi.mp4  0.010000
1     aamrozxzsq.mp4  0.604828
2     aaoqanfmgd.mp4  0.990000
3     aaqkmjtoby.mp4  0.010000
4     aarpyivfys.mp4  0.011211
...              ...       ...
3995  zzkhgelrxm.mp4  0.986409
3996  zzoqoqsqtf.mp4  0.010000
3997  zztotvpkjc.mp4  0.073738
3998  zztsycpujv.mp4  0.986140
3999  zzyawcrxmh.mp4  0.010000

[4000 rows x 2 columns]

## Loss

In [20]:
truth_labels = truth_df.label
predicted_labels = new_predicted_df.label

In [21]:
from sklearn.metrics import log_loss
loss = log_loss(truth_labels, predicted_labels)
loss

0.24769482198789888